name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION: 0.1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Gera Imagem
      run: make image
      
    - name: Login Docker Hub
      run: make login

    - name: Publica Imagem
      run: make publish
